### ISSUE TITLE
Fine-grained RK4 steps even when data are sparse

### ISSUE THREAD

**Issue by eschrom** [parksw3/fitode#16]
It appears that fitode takes the time steps observed in the data at face value: if there are big time steps between observations, then these big steps will also be taken by RK4 forward simulation during fitting. This allows big errors to accrue in the simulated values of state variables, leading to inaccurate parameter estimation.

For example, I simulated exponential growth with r=1 and x0=1, with poisson-distributed counts observed at Days 1, 3, 6, 8, 9, 11, 13, & 14. Running fitode yields about r=1.016 (close) and x0=3.477 (not close). Because 3.477 is much larger than the true x0, forward simulating using these parameters and a reasonable time step (say 0.1 days) gives a curve that systematically overestimates the data. However, if you forward simulate using these parameters and only the eight observed time steps, the model overlays the data well, albeit via seven coarse-grained line segments. To me, this indicates that fitode is forward simulating using the time steps observed in the data, rather than reasonable time steps to keep RK4 honest. In this case, the observed time steps of 1-2 days are too big to get accurate simulation out of RK4. Parameter estimates are consequently inaccurate. 

I thought I could fix this by adding the argument `solver.opts = list(method="rk4", times=seq(1, 14, by=0.1))` to fitode, telling it to use more fine-grained time steps for forward simulation. But this resulted in the dreaded `initial value in 'vmmin' is not finite` error. Perhaps I have simply botched my syntax for passing manually-chosen time steps to the ode forward simulator? Even so, is there a decent heuristic for choosing appropriately fine-grained forward simulation time steps by default, regardless of the time steps observed in the data? Or do you at least want to warn users about these dangers of naively fitting to sparse data?

In the meantime, a workaround is to include many fine-grained time steps in the data, with NA observations for most of them. Code demonstrating this whole issue, along with the workaround, is below.

```
# Totally simulated example to diagnose issues
## Use fitode package
library(fitode)
## Create sparse data and pseudo-dense data (dense time points but no observation at most of them)
days_sparse <- c(1, 3, 6, 8, 9, 11, 13, 14)
days_dense <- seq(0,14,by=0.1)
r1_true <- 1
x0_true <- 1
data_test_dense <- data.frame(day = days_dense, size = rpois(length(days_dense), x0_true*(exp(r1_true*days_dense))))
data_test_dense$size[!(data_test_dense$day %in% days_sparse)] <- NA
data_test_sparse <- data_test_dense[!is.na(data_test_dense$size), ]
ggplot2::ggplot(data_test_sparse) +
  ggplot2::geom_point(ggplot2::aes(x=day, y=size), size=5, color="black", shape=1, stroke=3) +
  ggplot2::xlab("Day") + ggplot2::ylab("Cell Count") + ggplot2::theme_bw() +
  ggplot2::ggtitle("Data") +
  ggplot2::theme(text = ggplot2::element_text(size=15))
## Build model
model_test <- odemodel(
  name="test",
  model=list(
    X1 ~ r1 * X1
  ),
  observation=list(
    size ~ dpois(lambda=X1)
  ),
  initial=list(
    X1 ~ X0
  ),
  par=c("r1", "X0")
)
## Fit model to sparse and pseudo-dense data separately
fit_test_sparse <- fitode(
  model=model_test,
  data=data_test_sparse,
  start=c(r1=1, X0=1),
  link=c(r1="log", X0="log"),
  tcol="day",
  solver.opts = list(method="rk4") #, times=seq(1, 14, by=0.1))
)
fit_test_dense <- fitode(
  model=model_test,
  data=data_test_dense,
  start=c(r1=1, X0=1),
  link=c(r1="log", X0="log"),
  tcol="day",
  solver.opts = list(method="rk4") #, times=seq(1, 14, by=0.1))
)
## Plot simulated data using sparse vs. dense parameters and sparse vs. dense timepoints
### Blue = parameters from fitting the sparse data; Red = parameters from fitting the pseudo-dense data
### Solid = forward simulation using sparse time points; Dashed = forward simulation using dense time points
sim_test_spr_spr <- simulate(model_test, parms = coef(fit_test_sparse), times = data_test_sparse$day)
sim_test_spr_dns <- simulate(model_test, parms = coef(fit_test_sparse), times = data_test_dense$day)
sim_test_dns_dns <- simulate(model_test, parms = coef(fit_test_dense), times = data_test_dense$day)
sim_test_dns_spr <- simulate(model_test, parms = coef(fit_test_dense), times = data_test_sparse$day)
ggplot2::ggplot() +
  ggplot2::geom_point(data = data_test_sparse, ggplot2::aes(x=day, y=size), size=5, color="black", shape=1, stroke=3) +
  ggplot2::geom_line(data = sim_test_spr_spr, ggplot2::aes(x=times, y=X1), linewidth=1.5, color="blue") +
  ggplot2::geom_line(data = sim_test_spr_dns, ggplot2::aes(x=times, y=X1), linewidth=1.5, color="blue", linetype="dashed") +
  ggplot2::geom_line(data = sim_test_dns_dns, ggplot2::aes(x=times, y=X1), linewidth=1.5, color="red", linetype="dashed") +
  ggplot2::geom_line(data = sim_test_dns_spr, ggplot2::aes(x=times, y=X1), linewidth=1.5, color="red") +
  ggplot2::xlab("Day") + ggplot2::ylab("Cell Count") + ggplot2::theme_bw() +
  ggplot2::ggtitle("Data + Models") + ggplot2::ylim(c(0,1250000)) +
  ggplot2::theme(text = ggplot2::element_text(size=15))
```

**Comment by bbolker** [comment]
I'm not sure why we chose `rk4` as the default solver: from the `deSolve` docs,

> ‘rk4’ and ‘euler’ are special versions of the two fixed step  solvers with less overhead and less functionality (e.g. no interpolation and no events) compared to the generic Runge-Kutta codes called by ‘ode’ resp. ‘rk’.

As far as I can tell at a quick read, `method = "rk"` uses a variable-step-size integrator by default.  I would give `solver.opts = list(method="rk")` and `solver.opts = list(method = "lsoda")` a try and see if it helps ...

**Comment by parksw3** [comment]
This is a known issue but I never documented it, sorry. `times=seq(1, 14, by=0.1)` doesn't work because `times` argument is already filled in by the data. What you need to use is actually `hini`, which is hidden inside `?rk`. So `solver.opts = list(method="rk4", hini=0.1)` will work. This still gives an estimate of 2.7 for `X0`. Note that `X0` estimate for the `fitode` corresponds to the value when `t=1` since the data starts from day 1, whereas `x0=1` for the data generation component starts at `t=0`. I'll add this to a warning as well. If you want to get X0 at time 0, then you have to back calculate manually:
```
confint(fit_test_sparse, parm=list(X0_real~X0*exp(-r1)))
```

Two more comments I want to make. 1. It's probably better to set the `link` argument during the model set up. And 2. the default link is log link so no need to specify it again.

@bbolker : `lsoda` had some other problems, which is why we decided on `rk4` (though I can't remember what the problem was).

Here's the full code demonstrating prediction at finer time scale (in case that's also helpful):

```
library(fitode)
data_test_sparse <- structure(list(day = c(1, 3, 6, 8, 9, 11, 13, 14), 
                                                         size = c(3L, 18L, 427L, 2960L, 7923L, 60146L, 442993L, 1202173L)), 
                                                         row.names = c(11L, 31L, 61L, 81L, 91L, 111L, 131L, 141L), class = "data.frame")

model_test <- odemodel(
	name="test",
	model=list(
		X1 ~ r1 * X1
	),
	observation=list(
		size ~ dpois(lambda=X1)
	),
	initial=list(
		X1 ~ X0
	),
	par=c("r1", "X0")
)
## Fit model to sparse and pseudo-dense data separately
fit_test_sparse <- fitode(
	model=model_test,
	data=data_test_sparse,
	start=c(r1=1, X0=1),
	tcol="day",
	solver.opts = list(method="rk4", hini=0.1)
)

pp <- predict(fit_test_sparse,
				times=seq(1, 14, by=0.1))

plot(data_test_sparse)
lines(pp$size)
```

**Comment by bbolker** [comment]
It might be worth trying "rk" (which isn't as complicated as LSODA but does have adaptive time steps) ...

**Comment by parksw3** [comment]
`rk` alone doesn't give good estimates. `lsoda` gives good estimates but throws a ton of warning during the fitting step. I'd say that setting `hini` manually is the most robust option.

**Comment by eschrom** [comment]
You are right that 2.7 is the correct x0 in the sparse case, because the first observed time point is t=1. In the pseudo-dense case, 1.0 is the correct x0, because the sham time points go back to t=0. 

Restricting to the sparse case and trying your suggestions:
`solver.opts = list(method="rk4", hini=0.1)` correctly yields x0=2.7.
`solver.opts = list(method="rk", hini=0.1)` correctly yields x0=2.7.
`solver.opts = list(method="rk4")` incorrectly yields x0=3.4.
`solver.opts = list(method="rk")` incorrectly yields x0=3.4.
`solver.opts = list(method="lsoda")` correctly yields x0=2.7, but with repeated warnings about poor choices of the `atol` and `rtol` parameters.

Of course this is just one test case, but some quick conclusions are:
- Solvers rk and rk4 produce nearly identical results, so I don't think rk is operating with variable step sizes, at least not very well. Both of them need to be told to use fine-grained steps when the data are sparse.
- Solver lsoda works, but it seems uncomfortably fussy to me. While its tolerance parameters are not super complex conceptually, the step size parameter for rk and rk4 is very satisfyingly intuitive.

So I think the solution is for the user to be on the lookout for sparse data, manually setting `hini` if need be. Still, warnings about dangerously sparse data, as well as x0 values that don't occur at t=0, could help.

Thank you both for your patience and help as I bumble through the learning process with fitode!

**Comment by parksw3** [comment]
To clarify, `rk` does use variable step sizes, with the default method being `rk45dp7`. It just makes a bad initial guess because the initial time step is large (which is why we still need to set a separate `hini`)...

**Comment by bbolker** [comment]
For the `data_test_sparse` case that @parksw3 gave above, without step sizes specified, `rk` is fast but wrong, `rk4` is slow but right, and `lsoda` is slow and right but complains a lot.

It's very interesting that this problem is this hard ...

```
system.time(fit1 <- fitode(
	model=model_test,
	data=data_test_sparse,
	start=c(r1=1, X0=1),
	tcol="day",
	solver.opts = list(method = "rk")))
## 0.47 sec

system.time(fit2 <- update(fit1, solver.opts = list(method = "rk4", hini=0.1)))
## 5.3 sec

system.time(fit3 <- update(fit1, solver.opts = list(method = "lsoda")))
## 6.1 sec

fitlist <- list(rk = fit1, rk4 = fit2, lsoda = fit3)

lapply(fitlist, coef) |> do.call(what="rbind")
##              r1       X0
## rk    1.0162215 3.465744
## rk4   0.9995787 2.733160
## lsoda 0.9995775 2.733164

tvec <- seq(1, 14, length.out = 501)
res <- lapply(list(fit1, fit2, fit3),
       function(x) predict(x, times = tvec)$size[,"estimate"])

res2 <- do.call("cbind", c(list(time = tvec), res))
matplot(res2[,"time"], res2[,-1], type = "l")
```

**Comment by eschrom** [comment]
Yes, it does seem like this should be easier than it is. On my system, both rk and rk4 are fast (~0.75") but wrong without `hini`, and slow (~4.9") but right with `hini`. So I think @parksw3 has the right conclusion - maybe it's just a matter of guiding the user about when to set `hini`. In any case, thank you!

**Comment by parksw3** [comment]
model fitting is not so easy after all... but really, the way to go for this specific problem (exponential curve fitting) is to just use glm and forget about ODEs...

**Comment by eschrom** [comment]
Yes, for this particular problem, glm may be best. But this particular problem is just a toy subset of a much more complex ODE system. So the solution you have offered for sparse data will prove to be essential, and I suspect other users will find themselves in a sparse data situation from time to time, too. So thank you again!

**Comment by parksw3** [comment]
No problem. By the way, I'm not sure if you've noticed or recognize me but we overlapped briefly in 2019 and part of 2020 before the pandemic. I usually go by Daniel and started my PhD in 2019 in Bryan's lab. I couldn't figure out a way to email or message you so I just wanted to leave a note here. I thought leaving this in stackoverflow would be too public, but github seems ok.

**Comment by eschrom** [comment]
I did recognize you! Feels like a long time ago. You have done such a
tremendous amount of great work! I hope you are excited to graduate soon.
If you'd ever like to connect privately, feel free to email me at
***@***.***

**Comment by parksw3** [comment]
Thanks for kind words! Email address doesn't show up on github (I guess privacy reasons). I'll ask Andrea and delete these messages later tonight as they seem maybe too private.

**Comment by parksw3** [comment]
Private conversations were deleted from this issue (making a note in case anyone else stumbles upon this issue in the future and wonders what happened). I'm closing the issue for now and implement the warning sign over the weekend.
