### ISSUE TITLE
missing tumorgrowth data

### ISSUE THREAD

**Issue by bbolker** [parksw3/fitode#3]
The vignette refers to a digitized tumor growth data set, but it doesn't seem to be included in the package anywhere (yet; presumably it exists but hasn't been committed/pushed yet?).  In a comment in the vignette @parksw3 asked

> Is it OK to extract data from a figure and put it in the package as long as we cite it? This seems like a good example here...

The answer to that question is "yes".

**Comment by parksw3** [comment]
I just pushed it!
